apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: flyt
spec:
  environments:
    - name: dev
      build:
        from: 446-migrate-to-reactflow
    - name: test
      build:
        from: 446-migrate-to-reactflow
    - name: qa
      build:
        from: 446-migrate-to-reactflow
    - name: prod
      build:
        from: 446-migrate-to-reactflow
    - name: old
      build:
        from: old
  components:
    - name: web
      dockerfileName: Dockerfile
      publicPort: http
      ports:
        - name: http
          port: 3000
      environmentConfig:
        - environment: dev
          variables:
            API_BASEURL: https://api-flyt-api-dev.radix.equinor.com
            AUTHORITY: https://login.microsoftonline.com/statoilsrm.onmicrosoft.com
            ENVIRONMENT: dev
        - environment: test
          variables:
            API_BASEURL: https://api-flyt-api-test.radix.equinor.com/
            AUTHORITY: https://login.microsoftonline.com/statoilsrm.onmicrosoft.com
            ENVIRONMENT: test
        - environment: qa
          variables:
            API_BASEURL: https://api-flyt-api-qa.radix.equinor.com
            AUTHORITY: https://login.microsoftonline.com/statoilsrm.onmicrosoft.com
            ENVIRONMENT: qa
        - environment: prod
          variables:
            API_BASEURL: https://api-flyt-api-prod.radix.equinor.com
            AUTHORITY: https://login.microsoftonline.com/statoilsrm.onmicrosoft.com
            ENVIRONMENT: prod
        - environment: old
          variables:
            API_BASEURL: https://api.statoil.com/app/vsm/prod
            AUDIENCE: 93cb35f6-8dd4-4dc1-8f44-d2e8dbd4be48
            AUTHORITY: https://login.microsoftonline.com/statoilsrm.onmicrosoft.com
            CLIENT_ID: 7b6f1bd7-ecb7-4e9b-b8a4-7a0a0804760d
            ENVIRONMENT: old
            SCOPE: 93cb35f6-8dd4-4dc1-8f44-d2e8dbd4be48/user_impersonation
